// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvtNJnQRm8LS3q0m9FpgfyWpZCYasgwp4',
    appId: '1:792040977590:web:347d8653a702982919a217',
    messagingSenderId: '792040977590',
    projectId: 'esp32-5226b',
    authDomain: 'esp32-5226b.firebaseapp.com',
    databaseURL: 'https://esp32-5226b-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-5226b.appspot.com',
    measurementId: 'G-01TSLD3EKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjpaPA8iKMIgpWpJV14cTuODveXVyjIDA',
    appId: '1:792040977590:android:ca6dfcc31190d3cb19a217',
    messagingSenderId: '792040977590',
    projectId: 'esp32-5226b',
    databaseURL: 'https://esp32-5226b-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-5226b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUMcvM9QNjq9UyiRyQFRtEMvN8YpLLEWA',
    appId: '1:792040977590:ios:6cd15a7caf6b133819a217',
    messagingSenderId: '792040977590',
    projectId: 'esp32-5226b',
    databaseURL: 'https://esp32-5226b-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-5226b.appspot.com',
    iosBundleId: 'com.example.mingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUMcvM9QNjq9UyiRyQFRtEMvN8YpLLEWA',
    appId: '1:792040977590:ios:bc76feac71bc7b9619a217',
    messagingSenderId: '792040977590',
    projectId: 'esp32-5226b',
    databaseURL: 'https://esp32-5226b-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-5226b.appspot.com',
    iosBundleId: 'com.example.mingApp.RunnerTests',
  );
}
